export const OPENAI_PROXY_URL =
  "https://azgplnfczforimmtpznx.supabase.co/functions/v1/openai-proxy";

export const SUPABASE_URL =
  "https://azgplnfczforimmtpznx.supabase.co";

export const SUPABASE_REST_API_URL =
  "https://supabase-rest-api.bangcoderpro.workers.dev";

export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6Z3BsbmZjemZvcmltbXRwem54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDY1NTEsImV4cCI6MjA3MTA4MjU1MX0.M9MF6xmAUjSE1VKTF_Q027luPrMjwRa8_m1iSVyF5TM";


export const STRIPE_WORKER_URL = "https://stripe-worker.bangcoderpro.workers.dev";

export const DOUBLE_COPY_THRESHOLD_MS = 500;

export const DEFAULT_SETTINGS = {
  mode: "translate",
  targetLang: "en-US",
  model: "gpt-4o-mini",
  rewritePrompt: "proofread",
};

export const MODELS = [
  { id: "gpt-4o-mini",       label: "⚡️ Economic - ChatGPT 4o-mini" },
  { id: "gpt-4.1-mini",      label: "🟢 Standard - ChatGPT 4.1-mini" },
  { id: "gpt-4.1",           label: "🧠 Professional - ChatGPT 4.1" },
  { id: "gpt-5-chat-latest", label: "🚀 Advanced - ChatGPT 5" },
];

export const REWRITE_PROMPTS = {
  proofread: "Fix grammar and spelling errors while preserving meaning.",
  formal:    "Rewrite in a formal, professional tone.",
  casual:    "Rewrite in a casual, friendly tone.",
  concise:   "Make it concise and to the point.",
  expand:    "Expand with more details and examples.",
};

export const REWRITE_TYPES = [
  {
    id: "proofread",
    label: "⚙️ Proofread",
    labelKo: "⚙️ 교정",
    description: "Fix grammar, spelling, and punctuation.",
    descriptionKo: "문법, 맞춤법, 구두점을 교정합니다.",
    prompt: "Please proofread the following text. Correct grammar, spelling, and punctuation errors.",
  },
  {
    id: "improve",
    label: "🔧 Improve",
    labelKo: "🔧 개선",
    description: "Make the sentence more natural.",
    descriptionKo: "문장을 더 자연스럽게 다듬습니다.",
    prompt: "Improve the fluency and clarity of the following sentence. Make it sound more natural while preserving its meaning.",
  },
  {
    id: "elaborate",
    label: "📚 Elaborate",
    labelKo: "📚 상세화",
    description: "Add more detail and context.",
    descriptionKo: "내용을 더 자세히 풀어서 설명합니다.",
    prompt: "Elaborate on the following sentence by adding relevant details or context. Expand the content without deviating from the original intent.",
  },
  {
    id: "clarify",
    label: "💡 Clarify",
    labelKo: "💡 명확화",
    description: "Make the meaning clearer.",
    descriptionKo: "의미가 더 명확하게 전달되도록 합니다.",
    prompt: "Clarify the following sentence. Rewrite it to remove ambiguity and ensure the meaning is easy to understand.",
  },
  {
    id: "paraphrase",
    label: "✏️ Paraphrase",
    labelKo: "✏️ 바꾸어쓰기",
    description: "Rewrite with different words.",
    descriptionKo: "같은 의미를 다른 표현으로 바꿉니다.",
    prompt: "Paraphrase the following sentence. Express the same meaning using different wording and structure.",
  },
  {
    id: "summarize",
    label: "📄 Summarize",
    labelKo: "📄 요약",
    description: "Extract and show the main idea.",
    descriptionKo: "핵심 내용을 간략하게 요약합니다.",
    prompt: "Summarize the following text by extracting and presenting only its main idea in a brief form.",
  },
];

// Source language list — iso_639_1_full_languages.json (simple codes, no regional variants)
// Used for source/input language dropdown. Matches franc detection output directly.
export const SOURCE_LANGUAGES = [
  { code: "ab", label: "Abkhaz (Аҧсуа)" },
  { code: "aa", label: "Afar (Afaraf)" },
  { code: "af", label: "Afrikaans (Afrikaans)" },
  { code: "ak", label: "Akan (Akan)" },
  { code: "sq", label: "Albanian (Shqip)" },
  { code: "am", label: "Amharic (አማርኛ)" },
  { code: "ar", label: "Arabic (العربية)" },
  { code: "an", label: "Aragonese (Aragonés)" },
  { code: "hy", label: "Armenian (Հայերեն)" },
  { code: "as", label: "Assamese (অসমীয়া)" },
  { code: "av", label: "Avaric (Авар мацӀ)" },
  { code: "ae", label: "Avestan (Avesta)" },
  { code: "ay", label: "Aymara (Aymar aru)" },
  { code: "az", label: "Azerbaijani (Azərbaycanca)" },
  { code: "bm", label: "Bambara (Bamanankan)" },
  { code: "ba", label: "Bashkir (Башҡорт теле)" },
  { code: "eu", label: "Basque (Euskara)" },
  { code: "be", label: "Belarusian (Беларуская)" },
  { code: "bn", label: "Bengali (বাংলা)" },
  { code: "bh", label: "Bihari (भोजपुरी)" },
  { code: "bi", label: "Bislama (Bislama)" },
  { code: "bs", label: "Bosnian (Bosanski)" },
  { code: "br", label: "Breton (Brezhoneg)" },
  { code: "bg", label: "Bulgarian (Български)" },
  { code: "my", label: "Burmese (မြန်မာစာ)" },
  { code: "ca", label: "Catalan (Català)" },
  { code: "ch", label: "Chamorro (Chamoru)" },
  { code: "ce", label: "Chechen (Нохчийн мотт)" },
  { code: "ny", label: "Chichewa (ChiCheŵa)" },
  { code: "zh", label: "Chinese (中文)" },
  { code: "cu", label: "Church Slavic (Ѩзыкъ словѣньскъ)" },
  { code: "cv", label: "Chuvash (Чӑваш чӗлхи)" },
  { code: "kw", label: "Cornish (Kernewek)" },
  { code: "co", label: "Corsican (Corsu)" },
  { code: "cr", label: "Cree (ᓀᐦᐃᔭᐍᐏᐣ)" },
  { code: "hr", label: "Croatian (Hrvatski)" },
  { code: "cs", label: "Czech (Čeština)" },
  { code: "da", label: "Danish (Dansk)" },
  { code: "dv", label: "Divehi (ދިވެހި)" },
  { code: "nl", label: "Dutch (Nederlands)" },
  { code: "dz", label: "Dzongkha (རྫོང་ཁ)" },
  { code: "en", label: "English (English)" },
  { code: "eo", label: "Esperanto (Esperanto)" },
  { code: "et", label: "Estonian (Eesti)" },
  { code: "ee", label: "Ewe (Eʋegbe)" },
  { code: "fo", label: "Faroese (Føroyskt)" },
  { code: "fj", label: "Fijian (Vakaviti)" },
  { code: "fi", label: "Finnish (Suomi)" },
  { code: "fr", label: "French (Français)" },
  { code: "ff", label: "Fulah (Fulfulde)" },
  { code: "gl", label: "Galician (Galego)" },
  { code: "lg", label: "Ganda (Luganda)" },
  { code: "ka", label: "Georgian (ქართული)" },
  { code: "de", label: "German (Deutsch)" },
  { code: "el", label: "Greek (Ελληνικά)" },
  { code: "gn", label: "Guarani (Avañe'ẽ)" },
  { code: "gu", label: "Gujarati (ગુજરાતી)" },
  { code: "ht", label: "Haitian (Kreyòl ayisyen)" },
  { code: "ha", label: "Hausa (Hausa)" },
  { code: "he", label: "Hebrew (עברית)" },
  { code: "hz", label: "Herero (Otjiherero)" },
  { code: "hi", label: "Hindi (हिन्दी)" },
  { code: "ho", label: "Hiri Motu (Hiri Motu)" },
  { code: "hu", label: "Hungarian (Magyar)" },
  { code: "is", label: "Icelandic (Íslenska)" },
  { code: "io", label: "Ido (Ido)" },
  { code: "ig", label: "Igbo (Asụsụ Igbo)" },
  { code: "id", label: "Indonesian (Bahasa Indonesia)" },
  { code: "ia", label: "Interlingua (Interlingua)" },
  { code: "ie", label: "Interlingue (Interlingue)" },
  { code: "iu", label: "Inuktitut (ᐃᓄᒃᑎᑐᑦ)" },
  { code: "ik", label: "Inupiaq (Iñupiaq)" },
  { code: "ga", label: "Irish (Gaeilge)" },
  { code: "it", label: "Italian (Italiano)" },
  { code: "ja", label: "Japanese (日本語)" },
  { code: "jv", label: "Javanese (Basa Jawa)" },
  { code: "kl", label: "Kalaallisut (Kalaallisut)" },
  { code: "kn", label: "Kannada (ಕನ್ನಡ)" },
  { code: "kr", label: "Kanuri (Kanuri)" },
  { code: "ks", label: "Kashmiri (कश्मीरी / كشميري)" },
  { code: "kk", label: "Kazakh (Қазақ тілі)" },
  { code: "km", label: "Khmer (ភាសាខ្មែរ)" },
  { code: "ki", label: "Kikuyu (Gĩkũyũ)" },
  { code: "rw", label: "Kinyarwanda (Ikinyarwanda)" },
  { code: "rn", label: "Kirundi (Ikirundi)" },
  { code: "kv", label: "Komi (Коми кыв)" },
  { code: "kg", label: "Kongo (Kikongo)" },
  { code: "ko", label: "Korean (한국어)" },
  { code: "ku", label: "Kurdish (Kurdî)" },
  { code: "kj", label: "Kwanyama (Kuanyama)" },
  { code: "ky", label: "Kyrgyz (Кыргызча)" },
  { code: "lo", label: "Lao (ພາສາລາວ)" },
  { code: "la", label: "Latin (Latina)" },
  { code: "lv", label: "Latvian (Latviešu)" },
  { code: "li", label: "Limburgish (Limburgs)" },
  { code: "ln", label: "Lingala (Lingála)" },
  { code: "lt", label: "Lithuanian (Lietuvių)" },
  { code: "lu", label: "Luba-Katanga (Tshiluba)" },
  { code: "lb", label: "Luxembourgish (Lëtzebuergesch)" },
  { code: "mk", label: "Macedonian (Македонски)" },
  { code: "mg", label: "Malagasy (Malagasy)" },
  { code: "ms", label: "Malay (Bahasa Melayu)" },
  { code: "ml", label: "Malayalam (മലയാളം)" },
  { code: "mt", label: "Maltese (Malti)" },
  { code: "gv", label: "Manx (Gaelg)" },
  { code: "mr", label: "Marathi (मराठी)" },
  { code: "mh", label: "Marshallese (Kajin M̧ajeļ)" },
  { code: "mn", label: "Mongolian (Монгол)" },
  { code: "mi", label: "Māori (Te Reo Māori)" },
  { code: "na", label: "Nauru (Ekakairũ Naoero)" },
  { code: "nv", label: "Navajo (Diné bizaad)" },
  { code: "ng", label: "Ndonga (Oshiwambo)" },
  { code: "ne", label: "Nepali (नेपाली)" },
  { code: "nd", label: "North Ndebele (isiNdebele)" },
  { code: "se", label: "Northern Sami (Davvisámegiella)" },
  { code: "no", label: "Norwegian (Norsk)" },
  { code: "nb", label: "Norwegian Bokmål (Bokmål)" },
  { code: "nn", label: "Norwegian Nynorsk (Nynorsk)" },
  { code: "ii", label: "Nuosu (ꆈꌠ꒿ Nuosuhxop)" },
  { code: "oc", label: "Occitan (Occitan)" },
  { code: "oj", label: "Ojibwa (ᐊᓂᔑᓈᐯᒧᐎᓐ)" },
  { code: "or", label: "Oriya (ଓଡ଼ିଆ)" },
  { code: "om", label: "Oromo (Afaan Oromoo)" },
  { code: "os", label: "Ossetian (Ирон æвзаг)" },
  { code: "pi", label: "Pali (Pāli)" },
  { code: "ps", label: "Pashto (پښتو)" },
  { code: "fa", label: "Persian (فارسی)" },
  { code: "pl", label: "Polish (Polski)" },
  { code: "pt", label: "Portuguese (Português)" },
  { code: "pa", label: "Punjabi (ਪੰਜਾਬੀ)" },
  { code: "qu", label: "Quechua (Runa Simi)" },
  { code: "ro", label: "Romanian (Română)" },
  { code: "rm", label: "Romansh (Rumantsch)" },
  { code: "ru", label: "Russian (Русский)" },
  { code: "sm", label: "Samoan (Gagana fa'a Sāmoa)" },
  { code: "sg", label: "Sango (Sängö)" },
  { code: "sa", label: "Sanskrit (संस्कृतम्)" },
  { code: "sc", label: "Sardinian (Sardu)" },
  { code: "gd", label: "Scottish Gaelic (Gàidhlig)" },
  { code: "sr", label: "Serbian (Српски)" },
  { code: "sn", label: "Shona (ChiShona)" },
  { code: "sd", label: "Sindhi (सिन्धी)" },
  { code: "si", label: "Sinhala (සිංහල)" },
  { code: "sk", label: "Slovak (Slovenčina)" },
  { code: "sl", label: "Slovenian (Slovenščina)" },
  { code: "so", label: "Somali (Soomaaliga)" },
  { code: "nr", label: "South Ndebele (isiNdebele)" },
  { code: "st", label: "Southern Sotho (Sesotho)" },
  { code: "es", label: "Spanish (Español)" },
  { code: "su", label: "Sundanese (Basa Sunda)" },
  { code: "sw", label: "Swahili (Kiswahili)" },
  { code: "ss", label: "Swati (SiSwati)" },
  { code: "sv", label: "Swedish (Svenska)" },
  { code: "tl", label: "Tagalog (Tagalog)" },
  { code: "ty", label: "Tahitian (Reo Tahiti)" },
  { code: "tg", label: "Tajik (Тоҷикӣ)" },
  { code: "ta", label: "Tamil (தமிழ்)" },
  { code: "tt", label: "Tatar (Татарча)" },
  { code: "te", label: "Telugu (తెలుగు)" },
  { code: "th", label: "Thai (ไทย)" },
  { code: "bo", label: "Tibetan (བོད་ཡིག)" },
  { code: "ti", label: "Tigrinya (ትግርኛ)" },
  { code: "to", label: "Tonga (Faka Tonga)" },
  { code: "ts", label: "Tsonga (Xitsonga)" },
  { code: "tn", label: "Tswana (Setswana)" },
  { code: "tr", label: "Turkish (Türkçe)" },
  { code: "tk", label: "Turkmen (Türkmençe)" },
  { code: "tw", label: "Twi (Twi)" },
  { code: "uk", label: "Ukrainian (Українська)" },
  { code: "ur", label: "Urdu (اردو)" },
  { code: "ug", label: "Uyghur (ئۇيغۇرچە)" },
  { code: "uz", label: "Uzbek (O'zbek)" },
  { code: "ve", label: "Venda (Tshivenda)" },
  { code: "vi", label: "Vietnamese (Tiếng Việt)" },
  { code: "vo", label: "Volapük (Volapük)" },
  { code: "wa", label: "Walloon (Walon)" },
  { code: "cy", label: "Welsh (Cymraeg)" },
  { code: "fy", label: "Western Frisian (Frysk)" },
  { code: "wo", label: "Wolof (Wolof)" },
  { code: "xh", label: "Xhosa (isiXhosa)" },
  { code: "yi", label: "Yiddish (ייִדיש)" },
  { code: "yo", label: "Yoruba (Yorùbá)" },
  { code: "za", label: "Zhuang (Saɯ cueŋƅ)" },
  { code: "zu", label: "Zulu (isiZulu)" },
];

// Target language list — iso_639_1_full_languages_rev.json (regional codes)
// Used for target/output language dropdown. Distinguishes en-US/en-GB, zh-CN/zh-TW, etc.
export const LANGUAGES = [
  { code: "ab", label: "Abkhaz (Аҧсуа)" },
  { code: "aa", label: "Afar (Afaraf)" },
  { code: "af", label: "Afrikaans (Afrikaans)" },
  { code: "ak", label: "Akan (Akan)" },
  { code: "sq", label: "Albanian (Shqip)" },
  { code: "am", label: "Amharic (አማርኛ)" },
  { code: "ar", label: "Arabic (العربية)" },
  { code: "an", label: "Aragonese (Aragonés)" },
  { code: "hy", label: "Armenian (Հայերեն)" },
  { code: "as", label: "Assamese (অসমীয়া)" },
  { code: "av", label: "Avaric (Авар мацӀ)" },
  { code: "ae", label: "Avestan (Avesta)" },
  { code: "ay", label: "Aymara (Aymar aru)" },
  { code: "az", label: "Azerbaijani (Azərbaycanca)" },
  { code: "bm", label: "Bambara (Bamanankan)" },
  { code: "ba", label: "Bashkir (Башҡорт теле)" },
  { code: "eu", label: "Basque (Euskara)" },
  { code: "be", label: "Belarusian (Беларуская)" },
  { code: "bn", label: "Bengali (বাংলা)" },
  { code: "bh", label: "Bihari (भोजपुरी)" },
  { code: "bi", label: "Bislama (Bislama)" },
  { code: "bs", label: "Bosnian (Bosanski)" },
  { code: "br", label: "Breton (Brezhoneg)" },
  { code: "bg", label: "Bulgarian (Български)" },
  { code: "my", label: "Burmese (မြန်မာစာ)" },
  { code: "ca", label: "Catalan (Català)" },
  { code: "ch", label: "Chamorro (Chamoru)" },
  { code: "ce", label: "Chechen (Нохчийн мотт)" },
  { code: "ny", label: "Chichewa (ChiCheŵa)" },
  { code: "zh-CN", label: "Chinese-Simplified (简体中文)" },
  { code: "zh-TW", label: "Chinese-Traditional (繁體中文)" },
  { code: "cu", label: "Church Slavic (Ѩзыкъ словѣньскъ)" },
  { code: "cv", label: "Chuvash (Чӑваш чӗлхи)" },
  { code: "kw", label: "Cornish (Kernewek)" },
  { code: "co", label: "Corsican (Corsu)" },
  { code: "cr", label: "Cree (ᓀᐦᐃᔭᐍᐏᐣ)" },
  { code: "hr", label: "Croatian (Hrvatski)" },
  { code: "cs", label: "Czech (Čeština)" },
  { code: "da", label: "Danish (Dansk)" },
  { code: "dv", label: "Divehi (ދިވެހި)" },
  { code: "nl", label: "Dutch (Nederlands)" },
  { code: "dz", label: "Dzongkha (རྫོང་ཁ)" },
  { code: "en-GB", label: "English-GB (English-GB)" },
  { code: "en-US", label: "English-US (English-US)" },
  { code: "eo", label: "Esperanto (Esperanto)" },
  { code: "et", label: "Estonian (Eesti)" },
  { code: "ee", label: "Ewe (Eʋegbe)" },
  { code: "fo", label: "Faroese (Føroyskt)" },
  { code: "fj", label: "Fijian (Vakaviti)" },
  { code: "fi", label: "Finnish (Suomi)" },
  { code: "fr-CA", label: "French-Canada (Français-Canada)" },
  { code: "fr-FR", label: "French-France (Français-France)" },
  { code: "ff", label: "Fulah (Fulfulde)" },
  { code: "gl", label: "Galician (Galego)" },
  { code: "lg", label: "Ganda (Luganda)" },
  { code: "ka", label: "Georgian (ქართული)" },
  { code: "de", label: "German (Deutsch)" },
  { code: "el", label: "Greek (Ελληνικά)" },
  { code: "gn", label: "Guarani (Avañe'ẽ)" },
  { code: "gu", label: "Gujarati (ગુજરાતી)" },
  { code: "ht", label: "Haitian (Kreyòl ayisyen)" },
  { code: "ha", label: "Hausa (Hausa)" },
  { code: "he", label: "Hebrew (עברית)" },
  { code: "hz", label: "Herero (Otjiherero)" },
  { code: "hi", label: "Hindi (हिन्दी)" },
  { code: "ho", label: "Hiri Motu (Hiri Motu)" },
  { code: "hu", label: "Hungarian (Magyar)" },
  { code: "is", label: "Icelandic (Íslenska)" },
  { code: "io", label: "Ido (Ido)" },
  { code: "ig", label: "Igbo (Asụsụ Igbo)" },
  { code: "id", label: "Indonesian (Bahasa Indonesia)" },
  { code: "ia", label: "Interlingua (Interlingua)" },
  { code: "ie", label: "Interlingue (Interlingue)" },
  { code: "iu", label: "Inuktitut (ᐃᓄᒃᑎᑐᑦ)" },
  { code: "ik", label: "Inupiaq (Iñupiaq)" },
  { code: "ga", label: "Irish (Gaeilge)" },
  { code: "it", label: "Italian (Italiano)" },
  { code: "ja", label: "Japanese (日本語)" },
  { code: "jv", label: "Javanese (Basa Jawa)" },
  { code: "kl", label: "Kalaallisut (Kalaallisut)" },
  { code: "kn", label: "Kannada (ಕನ್ನಡ)" },
  { code: "kr", label: "Kanuri (Kanuri)" },
  { code: "ks", label: "Kashmiri (कश्मीरी / كشميري)" },
  { code: "kk", label: "Kazakh (Қазақ тілі)" },
  { code: "km", label: "Khmer (ភាសាខ្មែរ)" },
  { code: "ki", label: "Kikuyu (Gĩkũyũ)" },
  { code: "rw", label: "Kinyarwanda (Ikinyarwanda)" },
  { code: "rn", label: "Kirundi (Ikirundi)" },
  { code: "kv", label: "Komi (Коми кыв)" },
  { code: "kg", label: "Kongo (Kikongo)" },
  { code: "ko", label: "Korean (한국어)" },
  { code: "ku", label: "Kurdish (Kurdî)" },
  { code: "kj", label: "Kwanyama (Kuanyama)" },
  { code: "ky", label: "Kyrgyz (Кыргызча)" },
  { code: "lo", label: "Lao (ພາສາລາວ)" },
  { code: "la", label: "Latin (Latina)" },
  { code: "lv", label: "Latvian (Latviešu)" },
  { code: "li", label: "Limburgish (Limburgs)" },
  { code: "ln", label: "Lingala (Lingála)" },
  { code: "lt", label: "Lithuanian (Lietuvių)" },
  { code: "lu", label: "Luba-Katanga (Tshiluba)" },
  { code: "lb", label: "Luxembourgish (Lëtzebuergesch)" },
  { code: "mk", label: "Macedonian (Македонски)" },
  { code: "mg", label: "Malagasy (Malagasy)" },
  { code: "ms", label: "Malay (Bahasa Melayu)" },
  { code: "ml", label: "Malayalam (മലയാളം)" },
  { code: "mt", label: "Maltese (Malti)" },
  { code: "gv", label: "Manx (Gaelg)" },
  { code: "mr", label: "Marathi (मराठी)" },
  { code: "mh", label: "Marshallese (Kajin M̧ajeļ)" },
  { code: "mn", label: "Mongolian (Монгол)" },
  { code: "mi", label: "Māori (Te Reo Māori)" },
  { code: "na", label: "Nauru (Ekakairũ Naoero)" },
  { code: "nv", label: "Navajo (Diné bizaad)" },
  { code: "ng", label: "Ndonga (Oshiwambo)" },
  { code: "ne", label: "Nepali (नेपाली)" },
  { code: "nd", label: "North Ndebele (isiNdebele)" },
  { code: "se", label: "Northern Sami (Davvisámegiella)" },
  { code: "no", label: "Norwegian (Norsk)" },
  { code: "nb", label: "Norwegian Bokmål (Bokmål)" },
  { code: "nn", label: "Norwegian Nynorsk (Nynorsk)" },
  { code: "ii", label: "Nuosu (ꆈꌠ꒿ Nuosuhxop)" },
  { code: "oc", label: "Occitan (Occitan)" },
  { code: "oj", label: "Ojibwa (ᐊᓂᔑᓈᐯᒧᐎᓐ)" },
  { code: "or", label: "Oriya (ଓଡ଼ିଆ)" },
  { code: "om", label: "Oromo (Afaan Oromoo)" },
  { code: "os", label: "Ossetian (Ирон æвзаг)" },
  { code: "pi", label: "Pali (Pāli)" },
  { code: "ps", label: "Pashto (پښتو)" },
  { code: "fa", label: "Persian (فارسی)" },
  { code: "pl", label: "Polish (Polski)" },
  { code: "pt-BR", label: "Portuguese-Brazil (Português-Brasil)" },
  { code: "pt-PT", label: "Portuguese-Portugal (Português-Portugal)" },
  { code: "pa", label: "Punjabi (ਪੰਜਾਬੀ)" },
  { code: "qu", label: "Quechua (Runa Simi)" },
  { code: "ro", label: "Romanian (Română)" },
  { code: "rm", label: "Romansh (Rumantsch)" },
  { code: "ru", label: "Russian (Русский)" },
  { code: "sm", label: "Samoan (Gagana fa'a Sāmoa)" },
  { code: "sg", label: "Sango (Sängö)" },
  { code: "sa", label: "Sanskrit (संस्कृतम्)" },
  { code: "sc", label: "Sardinian (Sardu)" },
  { code: "gd", label: "Scottish Gaelic (Gàidhlig)" },
  { code: "sr", label: "Serbian (Српски)" },
  { code: "sn", label: "Shona (ChiShona)" },
  { code: "sd", label: "Sindhi (सिन्धी)" },
  { code: "si", label: "Sinhala (සිංහල)" },
  { code: "sk", label: "Slovak (Slovenčina)" },
  { code: "sl", label: "Slovenian (Slovenščina)" },
  { code: "so", label: "Somali (Soomaaliga)" },
  { code: "nr", label: "South Ndebele (isiNdebele)" },
  { code: "st", label: "Southern Sotho (Sesotho)" },
  { code: "es", label: "Spanish (Español)" },
  { code: "su", label: "Sundanese (Basa Sunda)" },
  { code: "sw", label: "Swahili (Kiswahili)" },
  { code: "ss", label: "Swati (SiSwati)" },
  { code: "sv", label: "Swedish (Svenska)" },
  { code: "tl", label: "Tagalog (Tagalog)" },
  { code: "ty", label: "Tahitian (Reo Tahiti)" },
  { code: "tg", label: "Tajik (Тоҷикӣ)" },
  { code: "ta", label: "Tamil (தமிழ்)" },
  { code: "tt", label: "Tatar (Татарча)" },
  { code: "te", label: "Telugu (తెలుగు)" },
  { code: "th", label: "Thai (ไทย)" },
  { code: "bo", label: "Tibetan (བོད་ཡིག)" },
  { code: "ti", label: "Tigrinya (ትግርኛ)" },
  { code: "to", label: "Tonga (Faka Tonga)" },
  { code: "ts", label: "Tsonga (Xitsonga)" },
  { code: "tn", label: "Tswana (Setswana)" },
  { code: "tr", label: "Turkish (Türkçe)" },
  { code: "tk", label: "Turkmen (Türkmençe)" },
  { code: "tw", label: "Twi (Twi)" },
  { code: "uk", label: "Ukrainian (Українська)" },
  { code: "ur", label: "Urdu (اردو)" },
  { code: "ug", label: "Uyghur (ئۇيغۇرچە)" },
  { code: "uz", label: "Uzbek (O'zbek)" },
  { code: "ve", label: "Venda (Tshivenda)" },
  { code: "vi", label: "Vietnamese (Tiếng Việt)" },
  { code: "vo", label: "Volapük (Volapük)" },
  { code: "wa", label: "Walloon (Walon)" },
  { code: "cy", label: "Welsh (Cymraeg)" },
  { code: "fy", label: "Western Frisian (Frysk)" },
  { code: "wo", label: "Wolof (Wolof)" },
  { code: "xh", label: "Xhosa (isiXhosa)" },
  { code: "yi", label: "Yiddish (ייִדיש)" },
  { code: "yo", label: "Yoruba (Yorùbá)" },
  { code: "za", label: "Zhuang (Saɯ cueŋƅ)" },
  { code: "zu", label: "Zulu (isiZulu)" },
];

// Short ISO 639-1 codes (from franc) → regional codes used in LANGUAGES
const _LOCALE_OVERRIDES = { en: "en-US", zh: "zh-CN", fr: "fr-FR", pt: "pt-BR" };

export function resolveLocale(locale) {
  if (!locale) return "en-US";
  const exact = LANGUAGES.find(l => l.code === locale);
  if (exact) return exact.code;
  const short = locale.split("-")[0].toLowerCase();
  const exactShort = LANGUAGES.find(l => l.code === short);
  if (exactShort) return exactShort.code;
  if (_LOCALE_OVERRIDES[short]) return _LOCALE_OVERRIDES[short];
  const prefixMatch = LANGUAGES.find(l => l.code.startsWith(short + "-"));
  if (prefixMatch) return prefixMatch.code;
  return "en-US";
}
